/**
 * Runtime DOM Translation Engine Test Harness.
 * Provides a reference implementation conforming to the R2 engine specification,
 * and allows hot-swapping or testing against lib/runtime/engine.js when available.
 */

const PROTECTED_TAGS = new Set([
  'PRE', 'CODE', 'SAMP', 'KBD', 'SCRIPT', 'STYLE',
  'NOSCRIPT', 'TEMPLATE', 'TEXTAREA', 'INPUT'
]);

const PROTECTED_SELECTORS = [
  '.monaco-editor',
  '.monaco-diff-editor',
  '.cm-editor',
  '.cm-content',
  '.cm-line',
  '.xterm',
  '.xterm-screen',
  '.terminal',
  '[contenteditable="true"]',
  '[contenteditable="plaintext-only"]',
  '[data-notranslate="true"]',
  '.notranslate'
].join(',');

const TRANSLATABLE_ATTRS = new Set(['placeholder', 'title', 'aria-label']);

class ReferenceTranslationEngine {
  constructor(options = {}) {
    this.window = options.window;
    this.document = options.document;
    this.dicts = options.dicts || {};
    this.regexRules = (options.regexRules || []).map(r => ({
      re: new RegExp(r.pattern, r.flags || 'i'),
      replace: r.replace
    }));

    this.translatedCache = new WeakMap();
    this.originalCache = new WeakMap();
    this.isMutatingDom = false;
    this.isImeComposing = false;
    this.reentrancyCount = 0;
    this.translationMutationCount = 0;
    this.observedShadowRoots = new WeakSet();

    this.init();
  }

  init() {
    this.setupImeGuard();
    this.setupShadowDomHook();
    this.setupRootObserver();
  }

  setupImeGuard() {
    this.window.addEventListener('compositionstart', () => {
      this.isImeComposing = true;
    }, true);

    this.window.addEventListener('compositionend', () => {
      this.isImeComposing = false;
    }, true);
  }

  setupShadowDomHook() {
    const self = this;
    const proto = this.window.Element.prototype;
    const originalAttachShadow = proto.attachShadow;

    proto.attachShadow = function(init) {
      const shadowRoot = originalAttachShadow.call(this, init);
      try {
        if (!self.observedShadowRoots.has(shadowRoot)) {
          self.observedShadowRoots.add(shadowRoot);
          self.attachObserver(shadowRoot);
        }
      } catch (err) {
        console.error('[EngineHarness] Shadow hook error:', err);
      }
      return shadowRoot;
    };
  }

  setupRootObserver() {
    const root = this.document.documentElement;
    if (root) {
      this.attachObserver(root);
    }
  }

  attachObserver(target) {
    const observer = new this.window.MutationObserver(records => {
      this.handleMutations(records);
    });

    observer.observe(target, {
      childList: true,
      subtree: true,
      characterData: true,
      attributes: true,
      attributeFilter: ['placeholder', 'title', 'aria-label']
    });

    return observer;
  }

  isProtected(node) {
    if (!node) return true;
    let curr = node.nodeType === 1 ? node : node.parentElement;
    if (!curr) return false;

    while (curr) {
      if (PROTECTED_TAGS.has(curr.tagName)) {
        return true;
      }

      if (curr.isContentEditable) {
        return true;
      }

      if (curr.closest && curr.closest(PROTECTED_SELECTORS)) {
        return true;
      }

      const root = typeof curr.getRootNode === 'function' ? curr.getRootNode() : null;
      if (root && root !== curr && root.host) {
        curr = root.host;
      } else {
        break;
      }
    }

    return false;
  }

  lookupTranslation(text) {
    if (!text || typeof text !== 'string') return null;
    const trimmed = text.trim();
    if (!trimmed) return null;

    // 1. Static dictionary lookup
    for (const dict of Object.values(this.dicts)) {
      if (dict && typeof dict[trimmed] === 'string') {
        const replacement = dict[trimmed];
        return text.replace(trimmed, replacement);
      }
    }

    // 2. Dynamic regex rules
    for (const rule of this.regexRules) {
      if (rule.re.test(trimmed)) {
        return text.replace(rule.re, rule.replace);
      }
    }

    return null;
  }

  handleMutations(records) {
    if (this.isImeComposing) {
      // IME session active: suspend DOM translation
      return;
    }

    if (this.isMutatingDom) {
      // Mutex bail out: this mutation was generated by our own DOM write
      return;
    }

    for (const record of records) {
      if (record.type === 'characterData') {
        this.processTextNode(record.target);
      } else if (record.type === 'childList') {
        for (const added of record.addedNodes) {
          this.processSubtree(added);
        }
      } else if (record.type === 'attributes') {
        this.processAttribute(record.target, record.attributeName);
      }
    }
  }

  processTextNode(node) {
    if (this.isProtected(node)) return;

    const currentText = node.textContent;
    // Check WeakMap cache: if node already holds this translated text, skip
    if (this.translatedCache.get(node) === currentText) {
      return;
    }

    const translated = this.lookupTranslation(currentText);
    if (translated && translated !== currentText) {
      if (this.isMutatingDom) {
        this.reentrancyCount++;
        return;
      }
      this.isMutatingDom = true;
      try {
        this.originalCache.set(node, currentText);
        this.translatedCache.set(node, translated);
        node.textContent = translated;
        this.translationMutationCount++;
      } finally {
        this.isMutatingDom = false;
      }
    }
  }

  processAttribute(element, attrName) {
    if (!element || element.nodeType !== 1) return;
    const lower = attrName.toLowerCase();
    if (!TRANSLATABLE_ATTRS.has(lower)) return;

    // Skip placeholder on code editors or internal editor inputareas
    if (lower === 'placeholder') {
      if (element.classList && element.classList.contains('inputarea')) return;
      if (element.closest && element.closest('.monaco-editor, .cm-editor')) return;
    }

    const currentVal = element.getAttribute(lower);
    if (!currentVal) return;

    if (this.translatedCache.get(element) === currentVal) {
      return;
    }

    const translated = this.lookupTranslation(currentVal);
    if (translated && translated !== currentVal) {
      if (this.isMutatingDom) {
        this.reentrancyCount++;
        return;
      }
      this.isMutatingDom = true;
      try {
        this.translatedCache.set(element, translated);
        element.setAttribute(lower, translated);
        this.translationMutationCount++;
      } finally {
        this.isMutatingDom = false;
      }
    }
  }

  processSubtree(node) {
    if (node.nodeType === 3) {
      if (this.isProtected(node)) return;
      this.processTextNode(node);
    } else if (node.nodeType === 1) {
      // 1. Process translatable attributes (placeholder, title, aria-label)
      for (const attr of TRANSLATABLE_ATTRS) {
        if (node.hasAttribute(attr)) {
          this.processAttribute(node, attr);
        }
      }

      // 2. If element is a code container or input element, skip child nodes
      if (this.isProtected(node)) return;

      for (const child of node.childNodes) {
        this.processSubtree(child);
      }
    }
  }

  translateEntireDocument() {
    this.processSubtree(this.document.documentElement);
  }
}

let EngineClass = ReferenceTranslationEngine;
try {
  const realEngine = require('../../lib/runtime/engine');
  if (realEngine && realEngine.TranslationEngine) {
    EngineClass = realEngine.TranslationEngine;
  }
} catch (_) {}

function createTranslationHarness(env, dicts, regexRules) {
  return new EngineClass({
    window: env.window,
    document: env.document,
    dicts,
    regexRules
  });
}

module.exports = {
  ReferenceTranslationEngine,
  createTranslationHarness,
  PROTECTED_TAGS,
  PROTECTED_SELECTORS,
  TRANSLATABLE_ATTRS
};
